# @package _global_

# 默认配置 - 继承自其他配置文件
defaults:
  - model: default
  - train: stage1
  - _self_

# 基础配置
project_name: smartmoney
seed: null
debug: false

# 数据配置
data:
  dataset_type: "address_graph"  # 添加dataset_type配置，可选值: "address_graph" 或 "time_window"
  graphs_dir: data/graphs
  batch_size: 32
  num_workers: 4
  train_ratio: 0.8
  val_ratio: 0.1
  test_ratio: 0.1
  time_window: 3600  # 每个时间窗口秒数
  max_time_windows: 24  # 最大时间窗口数
  augmentation:  # 添加数据增强相关配置
    edge_drop_rate: 0.1
    feat_mask_rate: 0.1
    time_mask_prob: 0.05
    seq_mask_rate: 0.1  # 时间窗口数据集特有
    time_stretch_factor: 0.2  # 时间窗口数据集特有
    random_crop: true  # 时间窗口数据集特有

# 日志和输出
output:
  base_dir: outputs  # 添加base_dir作为输出的根目录
  model_dir: checkpoints
  log_dir: logs
  tensorboard_dir: logs/tensorboard
  results_dir: results
  plots_dir: plots
  save_every_epoch: 5

# 硬件
device: "cuda"  # "cuda" 或 "cpu"

# hydra配置
hydra:
  run:
    dir: ${output.log_dir}/${now:%Y-%m-%d_%H-%M-%S}
  sweep:
    dir: ${output.log_dir}/multirun/${now:%Y-%m-%d_%H-%M-%S}
    subdir: ${hydra.job.num}

# 杂项
verbose: true
use_wandb: false 